/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> }
 */
export async function seed(knex) {
  // Deletes ALL existing entries
  await knex('guestlist').del();
  await knex('guestlist').insert(
    [
      {
        "guest_firstname": "Kennedy",
        "guest_lastname": "Laing",
        "rsvp": null,
        "contact_email": null,
        "group": "family",
        "dietary_restrictions": null,
        "address": "207-380 Marina Drive",
        "city": "Chestermere",
        "province": "Alberta",
        "postal_code": "T1X 0B8"
      },
      {
        "guest_firstname": "Austin",
        "guest_lastname": "Bercier",
        "rsvp": null,
        "contact_email": null,
        "group": "family",
        "dietary_restrictions": null,
        "address": "207-380 Marina Drive",
        "city": "Chestermere",
        "province": "Alberta",
        "postal_code": "T1X 0B8"
      },
      {
        "guest_firstname": "Claudine",
        "guest_lastname": "Laing",
        "rsvp": null,
        "contact_email": null,
        "group": "family",
        "dietary_restrictions": null,
        "address": "366 Patterson Boulevard Southwest",
        "city": "Calgary",
        "province": "Alberta",
        "postal_code": "T3H 3N6"
      },
      {
        "guest_firstname": "Kevin",
        "guest_lastname": "Neish",
        "rsvp": null,
        "contact_email": null,
        "group": "family",
        "dietary_restrictions": null,
        "address": "366 Patterson Boulevard Southwest",
        "city": "Calgary",
        "province": "Alberta",
        "postal_code": "T3H 3N6"
      },
      {
        "guest_firstname": "Ted",
        "guest_lastname": "Laing",
        "rsvp": null,
        "contact_email": null,
        "group": "family",
        "dietary_restrictions": null,
        "address": "206-15392 16A Street",
        "city": "White Rock",
        "province": "British Columbia",
        "postal_code": "V4A 1S9"
      },
      {
        "guest_firstname": "Minoo",
        "guest_lastname": "Naeini",
        "rsvp": null,
        "contact_email": null,
        "group": "family",
        "dietary_restrictions": null,
        "address": "206-15392 16A Street",
        "city": "White Rock",
        "province": "British Columbia",
        "postal_code": "V4A 1S9"
      },
      {
        "guest_firstname": "Keeley",
        "guest_lastname": "Laing",
        "rsvp": null,
        "contact_email": null,
        "group": "family",
        "dietary_restrictions": null,
        "address": "14 Country Village Gate Northeast",
        "city": "Calgary",
        "province": "Alberta",
        "postal_code": "T3K 0L5"
      },
      {
        "guest_firstname": "Austin",
        "guest_lastname": "Greenall",
        "rsvp": null,
        "contact_email": null,
        "group": "family",
        "dietary_restrictions": null,
        "address": "14 Country Village Gate Northeast",
        "city": "Calgary",
        "province": "Alberta",
        "postal_code": "T3K 0L5"
      },
      {
        "guest_firstname": "Madison",
        "guest_lastname": "Laing",
        "rsvp": null,
        "contact_email": null,
        "group": "family",
        "dietary_restrictions": null,
        "address": "128 Willowmere Way",
        "city": "Chestermere",
        "province": "Alberta",
        "postal_code": "T1X 0E1"
      },
      {
        "guest_firstname": "Christopher",
        "guest_lastname": "Lassota",
        "rsvp": null,
        "contact_email": null,
        "group": "family",
        "dietary_restrictions": null,
        "address": "128 Willowmere Way",
        "city": "Chestermere",
        "province": "Alberta",
        "postal_code": "T1X 0E1"
      },
      {
        "guest_firstname": "Cooper",
        "guest_lastname": "Laing",
        "rsvp": null,
        "contact_email": null,
        "group": "family",
        "dietary_restrictions": null,
        "address": null,
        "city": null,
        "province": null,
        "postal_code": null
      },
      {
        "guest_firstname": "Rachel",
        "guest_lastname": "Bekker",
        "rsvp": null,
        "contact_email": null,
        "group": "family",
        "dietary_restrictions": null,
        "address": null,
        "city": null,
        "province": null,
        "postal_code": null
      },
      {
        "guest_firstname": "Raymond",
        "guest_lastname": "Lemire",
        "rsvp": null,
        "contact_email": null,
        "group": "family",
        "dietary_restrictions": null,
        "address": "520-255 The Donway West",
        "city": "North York",
        "province": "Ontario",
        "postal_code": "M3B 3M3"
      },
      {
        "guest_firstname": "Marie",
        "guest_lastname": "Lemire",
        "rsvp": null,
        "contact_email": null,
        "group": "family",
        "dietary_restrictions": null,
        "address": "520-255 The Donway West",
        "city": "North York",
        "province": "Ontario",
        "postal_code": "M3B 3M3"
      },
      {
        "guest_firstname": "Bernice",
        "guest_lastname": "Goulding",
        "rsvp": null,
        "contact_email": null,
        "group": "family",
        "dietary_restrictions": null,
        "address": "1509 Eagleview Drive",
        "city": "Pickering",
        "province": "Ontario",
        "postal_code": "L1V 5H2"
      },
      {
        "guest_firstname": "Edward",
        "guest_lastname": "Laing",
        "rsvp": null,
        "contact_email": null,
        "group": "family",
        "dietary_restrictions": null,
        "address": "1509 Eagleview Drive",
        "city": "Pickering",
        "province": "Ontario",
        "postal_code": "L1V 5H2"
      },
      {
        "guest_firstname": "Joyce",
        "guest_lastname": "Laing",
        "rsvp": null,
        "contact_email": null,
        "group": "family",
        "dietary_restrictions": null,
        "address": "550-24 Southport Street",
        "city": "Toronto",
        "province": "Ontario",
        "postal_code": "M6S 4Z1"
      },
      {
        "guest_firstname": "Gared",
        "guest_lastname": "Daniel",
        "rsvp": null,
        "contact_email": null,
        "group": "family",
        "dietary_restrictions": null,
        "address": "550-24 Southport Street",
        "city": "Toronto",
        "province": "Ontario",
        "postal_code": "M6S 4Z1"
      },
      {
        "guest_firstname": "Linda",
        "guest_lastname": "Laing",
        "rsvp": null,
        "contact_email": null,
        "group": "family",
        "dietary_restrictions": null,
        "address": "515-80 Front Street East",
        "city": "Toronto",
        "province": "Ontario",
        "postal_code": "M5E 1T4"
      },
      {
        "guest_firstname": "Scott",
        "guest_lastname": "Newnham",
        "rsvp": null,
        "contact_email": null,
        "group": "family",
        "dietary_restrictions": null,
        "address": "515-80 Front Street East",
        "city": "Toronto",
        "province": "Ontario",
        "postal_code": "M5E 1T4"
      },
      {
        "guest_firstname": "Lemire",
        "guest_lastname": "Family",
        "rsvp": null,
        "contact_email": null,
        "group": "family",
        "dietary_restrictions": null,
        "address": "111 Plateau Crescent",
        "city": "North York",
        "province": "Ontario",
        "postal_code": "M3C 1M9"
      },
      {
        "guest_firstname": "Melissa",
        "guest_lastname": "Fox",
        "rsvp": null,
        "contact_email": null,
        "group": "friends",
        "dietary_restrictions": null,
        "address": "12637 Lakeshore Road",
        "city": "Wainfleet",
        "province": "Ontario",
        "postal_code": "L0S 1V0"
      },
      {
        "guest_firstname": "Jim",
        "guest_lastname": "Graph",
        "rsvp": null,
        "contact_email": null,
        "group": "friends",
        "dietary_restrictions": null,
        "address": "12637 Lakeshore Road",
        "city": "Wainfleet",
        "province": "Ontario",
        "postal_code": "L0S 1V0"
      },
      {
        "guest_firstname": "Natalie",
        "guest_lastname": "Campbell",
        "rsvp": null,
        "contact_email": null,
        "group": "friends",
        "dietary_restrictions": null,
        "address": "1332 75 Avenue Southwest",
        "city": "Calgary",
        "province": "Alberta",
        "postal_code": "T2V 0S6"
      },
      {
        "guest_firstname": "Jason",
        "guest_lastname": "Bercier",
        "rsvp": null,
        "contact_email": null,
        "group": "family",
        "dietary_restrictions": null,
        "address": "254257 Range Road 284",
        "city": "Rocky View County",
        "province": "Alberta",
        "postal_code": "T1Z 0L2"
      },
      {
        "guest_firstname": "Evonna",
        "guest_lastname": "Bercier",
        "rsvp": null,
        "contact_email": null,
        "group": "family",
        "dietary_restrictions": null,
        "address": "254257 Range Road 284",
        "city": "Rocky View County",
        "province": "Alberta",
        "postal_code": "T1Z 0L2"
      },
      {
        "guest_firstname": "Ellesia",
        "guest_lastname": "Bercier",
        "rsvp": null,
        "contact_email": null,
        "group": "family",
        "dietary_restrictions": null,
        "address": "254257 Range Road 284",
        "city": "Rocky View County",
        "province": "Alberta",
        "postal_code": "T1Z 0L2"
      },
      {
        "guest_firstname": "Matthew",
        "guest_lastname": "Premuzak",
        "rsvp": null,
        "contact_email": null,
        "group": "family",
        "dietary_restrictions": null,
        "address": "254257 Range Road 284",
        "city": "Rocky View County",
        "province": "Alberta",
        "postal_code": "T1Z 0L2"
      },
      {
        "guest_firstname": "Ava",
        "guest_lastname": "Bercier",
        "rsvp": null,
        "contact_email": null,
        "group": "family",
        "dietary_restrictions": null,
        "address": "254257 Range Road 284",
        "city": "Rocky View County",
        "province": "Alberta",
        "postal_code": "T1Z 0L2"
      },
      {
        "guest_firstname": "Manoual",
        "guest_lastname": "Yacop",
        "rsvp": null,
        "contact_email": null,
        "group": "family",
        "dietary_restrictions": null,
        "address": "254257 Range Road 284",
        "city": "Rocky View County",
        "province": "Alberta",
        "postal_code": "T1Z 0L2"
      },
      {
        "guest_firstname": "Nicholas",
        "guest_lastname": "Bercier",
        "rsvp": null,
        "contact_email": null,
        "group": "family",
        "dietary_restrictions": null,
        "address": "254257 Range Road 284",
        "city": "Rocky View County",
        "province": "Alberta",
        "postal_code": "T1Z 0L2"
      },
      {
        "guest_firstname": "Courtney",
        "guest_lastname": "Syntak",
        "rsvp": null,
        "contact_email": null,
        "group": "family",
        "dietary_restrictions": null,
        "address": "254257 Range Road 284",
        "city": "Rocky View County",
        "province": "Alberta",
        "postal_code": "T1Z 0L2"
      },
      {
        "guest_firstname": "Guiseppe",
        "guest_lastname": "Sartore",
        "rsvp": null,
        "contact_email": null,
        "group": "family",
        "dietary_restrictions": null,
        "address": "254257 Range Road 284",
        "city": "Rocky View County",
        "province": "Alberta",
        "postal_code": "T1Z 0L2"
      },
      {
        "guest_firstname": "Susan",
        "guest_lastname": "Sartore",
        "rsvp": null,
        "contact_email": null,
        "group": "family",
        "dietary_restrictions": null,
        "address": "254257 Range Road 284",
        "city": "Rocky View County",
        "province": "Alberta",
        "postal_code": "T1Z 0L2"
      },
      {
        "guest_firstname": "Rita",
        "guest_lastname": "Bercier",
        "rsvp": null,
        "contact_email": null,
        "group": "family",
        "dietary_restrictions": null,
        "address": "111 Whitehaven Road Northeast",
        "city": "Calgary",
        "province": "Alberta",
        "postal_code": "T1Y 6A6"
      },
      {
        "guest_firstname": "Daniel",
        "guest_lastname": "McKee",
        "rsvp": null,
        "contact_email": null,
        "group": "friends",
        "dietary_restrictions": null,
        "address": "216 Hawkmere Close",
        "city": "Chestermere",
        "province": "Alberta",
        "postal_code": "T1X 0C1"
      },
      {
        "guest_firstname": "Matthew",
        "guest_lastname": "Solda",
        "rsvp": null,
        "contact_email": null,
        "group": "friends",
        "dietary_restrictions": null,
        "address": null,
        "city": null,
        "province": null,
        "postal_code": null
      },
      {
        "guest_firstname": "André",
        "guest_lastname": "Rodriques",
        "rsvp": null,
        "contact_email": null,
        "group": "friends",
        "dietary_restrictions": null,
        "address": "214 Westchester Way",
        "city": "Chestermere",
        "province": "Alberta",
        "postal_code": "T1X 1E2"
      },
      {
        "guest_firstname": "Chase",
        "guest_lastname": "Lamoureux",
        "rsvp": null,
        "contact_email": null,
        "group": "friends",
        "dietary_restrictions": null,
        "address": "247 Springmere Close",
        "city": "Chestermere",
        "province": "Alberta",
        "postal_code": "T1X 1K1"
      },
      {
        "guest_firstname": "Kyle",
        "guest_lastname": "Lutes",
        "rsvp": null,
        "contact_email": null,
        "group": "friends",
        "dietary_restrictions": null,
        "address": "11246 75A Avenue",
        "city": "Grande Prairie",
        "province": "Alberta",
        "postal_code": "T8W 0C3"
      },
      {
        "guest_firstname": "Madison",
        "guest_lastname": "James",
        "rsvp": null,
        "contact_email": null,
        "group": "friends",
        "dietary_restrictions": null,
        "address": "11246 75A Avenue",
        "city": "Grande Prairie",
        "province": "Alberta",
        "postal_code": "T8W 0C3"
      },
      {
        "guest_firstname": "Natasha",
        "guest_lastname": "Eden",
        "rsvp": null,
        "contact_email": null,
        "group": "friends",
        "dietary_restrictions": null,
        "address": "601-55 9A Street Northeast",
        "city": "Calgary",
        "province": "Alberta",
        "postal_code": "T2E 7J6"
      },
      {
        "guest_firstname": "Jay",
        "guest_lastname": "Peris",
        "rsvp": null,
        "contact_email": null,
        "group": "friends",
        "dietary_restrictions": null,
        "address": "601-55 9A Street Northeast",
        "city": "Calgary",
        "province": "Alberta",
        "postal_code": "T2E 7J6"
      },
      {
        "guest_firstname": "Ernest",
        "guest_lastname": "McCutcheon",
        "rsvp": null,
        "contact_email": null,
        "group": "friends",
        "dietary_restrictions": null,
        "address": "419 Brookmere Crescent Southwest",
        "city": "Calgary",
        "province": "Alberta",
        "postal_code": "T2W 2R2"
      },
      {
        "guest_firstname": "Melissa",
        "guest_lastname": "McCutcheon",
        "rsvp": null,
        "contact_email": null,
        "group": "friends",
        "dietary_restrictions": null,
        "address": "419 Brookmere Crescent Southwest",
        "city": "Calgary",
        "province": "Alberta",
        "postal_code": "T2W 2R2"
      },
      {
        "guest_firstname": "James",
        "guest_lastname": "Hagel",
        "rsvp": null,
        "contact_email": null,
        "group": "friends",
        "dietary_restrictions": null,
        "address": "316 Windermere Drive",
        "city": "Chestemere",
        "province": "Alberta",
        "postal_code": "T1X 0B9"
      }
    ]
    );
};
